accounts/urls.py
from django.conf.urls import url, patterns
from accounts.views import RegisterView, ProfileView, LoginView, LogoutView,RegisterSuccessView,EditProfileView,FollowUser

urlpatterns=patterns('',
    url(r'^register/$',RegisterView.as_view(),name="register"),
    url(r'^registersuccess/$',RegisterSuccessView.as_view(),name="register_success"),
    url(r'^login/$',LoginView.as_view(), name="login"),
    url(r'^logout/$', LogoutView.as_view(), name="logout"),
    url(r'^profile/(?P<username>[-\w\d]+)/$',ProfileView.as_view(),name="profile"),
    url(r'^profile/$',ProfileView.as_view(),name="myprofile"),
    url(r'^changepassword/$',ProfileView.as_view(),name="change_password"),
    url(r'^editprofile/$',EditProfileView.as_view(),name="edit_profile"),
    url(r'^follow/$',FollowUser.as_view())
)

hoidap/urls.py
from django.conf.urls import include, url, patterns
from django.contrib import admin
from .views import Index,SearchAjax
import settings
urlpatterns = [
    # Examples:
    # url(r'^$', 'hoidap.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^$',Index.as_view(), name="index"),
    url(r'^user/',include('accounts.urls', namespace="user")),
    url(r'^tag/', include('tag.urls',namespace="tag")),
    url(r'^question/', include('question.urls',namespace="question")),
    url(r'^message/', include('messenger.urls', namespace="message")),
    url(r'^notification/', include('notification.urls', namespace="notification")),
    url(r'^search/ajax/$',SearchAjax.as_view(),name="searchajax"),
]
#media files
if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += patterns('',
        (r'^media/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.MEDIA_ROOT}))

#Change title admin    
admin.site.site_header = "Hoi dap"

question/urls.py
from django.conf.urls import url, patterns
from .views import AddQuestionView, QuestionView, AddAnswerView, VoteView

urlpatterns=patterns('',
    url(r'^add/$', AddQuestionView.as_view(), name="add"),
    url(r'^(?P<questionid>\d+)-(?P<slug>[-\w\d]+)/$',QuestionView.as_view(), name="detail"),
    url(r'^(?P<questionid>\d+)-(?P<slug>[-\w\d]+)/answer/$',AddAnswerView.as_view(), name="answer"),
    url(r'^vote/$', VoteView.as_view(), name="vote"),
    )

tag/urls.py
from django.conf.urls import url, patterns
from .views import TagView, AddTagView, TagAllView,TagSearchAjaxView
from accounts.views import FollowTag
urlpatterns=patterns('',
    url(r'^all/$', TagAllView.as_view(), name="all"),
    url(r'^addtag/$', AddTagView.as_view(), name="add"),    
    url(r'^(?P<tagid>\d+)-(?P<slug>[-\w\d]+)/$',TagView.as_view(), name="tag_detail"),
    url(r'^follow/$', FollowTag.as_view(),name="follow_tag"),
    url(r'^search/', TagSearchAjaxView.as_view(),name="search"),
    )

question/models.py
from __future__ import unicode_literals
from django.db import models
from django.template.defaultfilters import slugify
from django.core.urlresolvers import reverse
from accounts.models import UserProfile
from tag.models import Tag
# Create your models here.

class CommonFields(models.Model):
    content=models.TextField()
    is_active=models.BooleanField(default=True)
    create=models.DateTimeField(auto_now_add=True)
    modify=models.DateTimeField(auto_now=True)
    votes_count=models.IntegerField(default=0)
    downvotes_count=models.IntegerField(default=0)
    rank=models.FloatField(default=0)

    @property
    def content_bref(self):
        return self.content[:100].encode('utf8')
    @property
    def content_bref300(self):
        return self.content[:300].encode('utf8')
    
    class Meta:
        abstract = True

class Question(CommonFields):
    title=models.CharField(blank=False, max_length=255)
    author=models.ForeignKey(UserProfile, related_name='user_questions')
    tags=models.ManyToManyField(Tag, related_name='tag_questions') 
    slug=models.SlugField(blank=True, max_length=255)
    votes=models.ManyToManyField(UserProfile, related_name='user_question_votes')
    downvotes=models.ManyToManyField(UserProfile, related_name='user_question_downvotes')
    
    def __str__(self):
        return self.title.encode('utf8')

    def save(self,*args,**kwargs):
        if not self.pk:
            self.slug=slugify(self.title)
        if self.pk:
            self.votes_count=self.votes.all().count()
            self.downvotes_count=self.downvotes.all().count()
            self.rank=self.votes_count*0.01-self.downvotes_count*0.05
        super(Question,self).save(*args,**kwargs)

    def get_absolute_url(self):
        return reverse('question:detail', args=(self.pk, self.slug))

    def get_cname(self):
        return self.__class__.__name__

class Answer(CommonFields):
    author=models.ForeignKey(UserProfile, related_name='user_answers')
    question=models.ForeignKey(Question, related_name='question_answers')
    votes=models.ManyToManyField(UserProfile, related_name='user_answer_votes')
    downvotes=models.ManyToManyField(UserProfile, related_name='user_answer_downvotes')
    
    def __str__(self):
        return self.content[:100].encode('utf8')

    def save(self, *args, **kwargs):
        if self.pk:
            self.votes_count=self.votes.all().count()
            self.downvotes_count=self.downvotes.all().count()
            self.rank=self.votes_count*0.01-self.downvotes_count*0.05
        super(Answer,self).save(*args,**kwargs)

question/forms.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from .models import Question
class AnswerFrom(forms.Form):
    content=forms.CharField(widget=forms.Textarea(attrs={'rows': 6}), label='Trả lời')
    def __init__(self, *args, **kwargs):
        super(AnswerFrom, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_id = 'answer'
        self.helper.form_method = 'post'
        self.helper.form_action = 'answer/'
        self.helper.add_input(Submit('submit', 'Trả lời'))

class QuestionForm(forms.Form):
    title=forms.CharField(required=True, label='Question')
    content=forms.CharField(label='Content', widget=forms.Textarea(), required=False)
    tags=forms.CharField(label='Topics')

    def clean_title(self):
        title=self.cleaned_data['title'].strip()
        if title[len(title)-1]!='?':
            title+='?'
        return title

    def clean_tags(self):
        tags=self.cleaned_data['tags'].strip()
        tags=tags.strip(',')
        tags=tags.split(',')
        for i in range(len(tags)):
            tags[i]=tags[i].lower().title()
        return tags

    def __init__(self, *args, **kwargs):
        super(QuestionForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_id = 'question'
        self.helper.form_method = 'post'
        self.helper.form_action = 'question:add'
        self.helper.add_input(Submit('submit', 'Submit'))

question/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
import json
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.core.context_processors import csrf
from django.views.generic import View
from django.core.exceptions import ObjectDoesNotExist
from .models import Question, Answer
from .forms import AnswerFrom,QuestionForm
from tag.models import Tag
from notification.models import Notification
from utils.login_require import LoginRequiredMixin
# Create your views here.

class QuestionView(View):
    def get(self, request, questionid, slug):
        args={}
        try:
            question=Question.objects.get(pk=questionid)
            args['question']=question
            answers=question.question_answers.all().order_by("-rank")
            args['answers']=answers
            if request.user.is_authenticated():                
                answerform=AnswerFrom()
                args['answerform']=answerform
            args.update(csrf(request))
        except ObjectDoesNotExist:            
            pass
        return render(request,'question_detail.html',args)

class AddQuestionView(LoginRequiredMixin,View):
    def get(self,request):
        args={}
        args.update(csrf(request))
        return render(request, 'question_add.html', args)
    
    def post(self,request):
        form=QuestionForm(data=request.POST)
        if form.is_valid():
            question=Question(title=form.cleaned_data['title'],content=form.cleaned_data['content'])
            question.author=request.user.profile
            question.save()
            for tagtitle in form.cleaned_data['tags']:
                try:
                    tag=Tag.objects.get(name=tagtitle)
                except ObjectDoesNotExist:
                    tag=Tag()
                    tag.name=tagtitle
                    tag.save()
                question.tags.add(tag)
                tag.save()
            question.author.rank+=0.01
            question.save()
            question.author.save()
            #notification
            users_notification=[]
            for tag in question.tags.all():
                if tag.tag_followers.all().count() > 0:
                    for profile in tag.tag_followers.all():
                        if profile!=request.user.profile and profile not in users_notification:
                            #create notification
                            notification=Notification()
                            notification.sender=request.user.profile
                            notification.recipient=profile
                            notification.action='addquestion'
                            notification.content_object=question
                            notification.save()
                            users_notification.append(profile)
            for follower in request.user.profile.followers.all():
                if follower not in users_notification:
                    notification=Notification()
                    notification.sender=request.user.profile
                    notification.recipient=follower
                    notification.action='addquestion'
                    notification.content_object=question
                    notification.save()
            return HttpResponseRedirect(reverse('question:detail',args=(question.pk, question.slug)))
        else:
            args={}
            args['form']=form
            args.update(csrf(request))
            return render(request,'question_add.html',args)

class AddAnswerView(LoginRequiredMixin,View):
    def post(self,request,questionid=None, slug=None):
        if questionid:
            form=AnswerFrom(data=request.POST)
            if form.is_valid():                
                try:
                    question=Question.objects.get(pk=questionid)
                    answer=Answer(content=form.cleaned_data['content'], question=question, author=request.user.profile)
                    answer.save()
                    answer.author.rank+=0.01
                    answer.author.save()
                    #notification
                    if question.author!=request.user.profile:
                        notification=Notification()
                        notification.sender=request.user.profile
                        notification.recipient=question.author
                        notification.action="answer"
                        notification.content_object=answer
                        notification.save()
                except ObjectDoesNotExist:
                    pass
        return HttpResponseRedirect(reverse('question:detail',args=(questionid, slug)))

class VoteView(View):
    def post(self, request):
        message={}
        if request.user.is_authenticated():
            objectid=request.POST.get('objectid','')
            objecttype=request.POST.get('objecttype','')
            votetype=request.POST.get('votetype','')
            if objectid and objecttype and votetype:
                if objecttype=='question':
                    currentobject=Question.objects.get(pk=objectid);
                elif objecttype=='answer':
                    currentobject=Answer.objects.get(pk=objectid);
                if currentobject:
                    if votetype=="vote":
                        if request.user.profile in currentobject.votes.all():
                            message['status']='False'
                            message['message']="Bạn chỉ được thích một lần"
                        else:
                            currentobject.votes.add(request.user.profile)
                            currentobject.save()
                            currentobject.author.rank+=0.01
                            currentobject.author.save()
                            message['status']='OK'
                            message['message']=""
                            message['votes_count']=currentobject.votes_count
                    elif votetype=="downvote":
                        if request.user.profile in currentobject.downvotes.all():
                            message['status']='False'
                            message['message']="Bạn chỉ được không thích một lần"
                        else:
                            currentobject.downvotes.add(request.user.profile)                            
                            currentobject.save()
                            currentobject.author.rank-=0.05
                            currentobject.author.save()
                            message['status']='OK'
                            message['message']=""
                            message['votes_count']=currentobject.downvotes_count
                    #notification
                    if currentobject.author!=request.user.profile:
                        notification=Notification()
                        notification.action=votetype
                        notification.sender=request.user.profile
                        notification.recipient=currentobject.author
                        notification.content_object=currentobject
                        notification.save()
                else:
                    message['status']='False'
                    message['message']="{} không tồn tại".format(objecttype)
            else:
                message['status']='False'
                message['message']='Thông tin không chính xác'
        else:
            message['status']='False'
            message['message']='Bạn cần đăng nhập'
        return HttpResponse(json.dumps(message), content_type = "application/json")

question/templates/answer.html
<li class="answer item row">
    <div class="author col-md-1">
        <a class="thumb" href="{% url 'user:profile' answer.author.username%}">
            {%if answer.author.avatar %}
                <img class="img-circle" src="{{ MEDIA_URL}}{{answer.author.avatar}}"/>
            {%else%}
                <img class="img-circle" src="{{ MEDIA_URL}}/profiles/noimage.png"/>
            {%endif%}             
        </a>     
    </div>
    <div class="col-md-11">
        <a href="{% url 'user:profile' answer.author.username%}">
            {{answer.author.fullname|escape}}
        </a>
        <div class="answer-content">
            <p>{{answer.content|escape}}</p>
        </div>
        <div class="social row">
            <div class="col-md-2 vote">
                <button class="btn btn-default btn-xs vote">
                    <input type="hidden" name="objectid" value="{{ answer.pk }}"/>
                    <input type="hidden" name="votetype" value="vote"/>
                    <input type="hidden" name="objecttype" value="answer"/>
                    <span class="glyphicon glyphicon-thumbs-up"></span>
                    <span class="follow_label">
                    Thích
                    </span>
                    <span class="votes_count">{{answer.votes_count}}</span>
                </button>  
            </div>
            <div class="col-md-2 vote">
                <button class="btn btn-default btn-xs vote">
                    <input type="hidden" name="objectid" value="{{ answer.pk }}"/>
                    <input type="hidden" name="votetype" value="downvote"/>
                    <input type="hidden" name="objecttype" value="answer"/>
                    <span class="glyphicon glyphicon-thumbs-down"></span>
                    <span class="follow_label">
                    Không thích
                    </span>
                    <span class="votes_count">{{answer.downvotes_count}}</span>
                </button>
            </div>
        </div>
    </div>    
</li>

question/templates/question.html
<div class="item question">
    <h4><a href="{% url 'question:detail' question.pk question.slug%}">
        {{question.title|escape}}
    </a></h4>
    <div class="author">
        <a class="thumb" href="{% url 'user:profile' question.author.username%}">
            {%if question.author.avatar %}
                <img class="img-circle" src="{{ MEDIA_URL}}{{question.author.avatar}}"/>
            {%else%}
                <img class="img-circle" src="{{ MEDIA_URL}}/profiles/noimage.png"/>
            {%endif%}                
        </a>       
        <a href="{% url 'user:profile' question.author.username%}">
            {{question.author.fullname|escape}}    
        </a>
    </div>
    <p>{{question.content_bref300}}</p>
    <div class="social row">
        <div class="col-md-2 vote">
            <button class="btn btn-default btn-xs vote">
                <input type="hidden" name="objectid" value="{{ question.pk }}"/>
                <input type="hidden" name="votetype" value="vote"/>
                <input type="hidden" name="objecttype" value="question"/>
                <span class="glyphicon glyphicon-thumbs-up"></span>
                <span class="follow_label">
                Thích
                </span>
                <span class="votes_count">{{question.votes_count}}</span>
            </button>  
        </div>
        <div class="col-md-2 vote">
            <button class="btn btn-default btn-xs vote">
                <input type="hidden" name="objectid" value="{{ question.pk }}"/>
                <input type="hidden" name="votetype" value="downvote"/>
                <input type="hidden" name="objecttype" value="question"/>
                <span class="glyphicon glyphicon-thumbs-down"></span>
                <span class="follow_label">
                Không thích
                </span>
                <span class="votes_count">{{question.downvotes_count}}</span>
            </button>
        </div>
        <div class="col-md-2">
            <a href="{% url 'question:detail' question.pk question.slug %}#answers" class="btn btn-link btn-xs">
            <span class="glyphicon glyphicon-comment"></span> Answers({{question.question_answers.all.count}})
            </a>
        </div>
        <div class="col-md-6">
            {%if question.tags.all%}
                <span class="glyphicon glyphicon-tags"></span> :
                {%for tag in question.tags.all%}
                    <a href="{% url 'tag:tag_detail' tag.pk tag.slug %}">{{tag.name}}</a>,
                {%endfor%}
            {%endif%}
        </div>
    </div>
</div>
<hr/>

question/templates/question_add.html
{%extends "question_base.html"%}
{%load staticfiles%}
{%block extra_js%}
    <script type="text/javascript" src="{% static "js/tag-it.min.js" %}"></script>
    <script type="text/javascript">
    $(document).ready(function() {        
        $('#topics').tagit({
            removeConfirmation: true,
            singleField: true,
            singleFieldNode: $('#id_tags'),
            allowSpaces: true,
            minLength: 2,
            singleFieldDelimiter: ',',
            allowDuplicates:false,
            tagSource: function( request, response ) {
                var data={'term':request.term}
                $.ajax({
                    "url": "/tag/search/", 
                    "type": "POST",
                    "data": data,       
                    "dataType": "json",
                    success: function( data ) {
                        response( $.map( data, function( item ) {
                            return {
                                label:item,
                                value:item
                            }
                        }));
                    }
                    })
            },
            autocomplete: {
               delay: 200,
               minLength: 3               
            }
        });        
    });    
    </script>
{%endblock%}
{%block extra_css%}
    <link rel="stylesheet" type="text/css" href="{% static "css/jquery.tagit.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "css/tagit.ui-zendesk.css" %}">    
{%endblock%}
{%load crispy_forms_tags%}
{%block title%}Đặt câu hỏi{%endblock%}
{%block content%}
<form action="/question/add/" id="question" method="post">
{%csrf_token%}
    <div id="div_id_title" class="form-group">
        <label for="id_title" class="control-label  requiredField">Câu hỏi
            <span class="asteriskField">*</span> 
        </label> 
        <div class="controls ">
            <input class="textinput textInput form-control" id="id_title" name="title" type="text"> 
        </div>
    </div>
    <div id="div_id_content" class="form-group">
        <label for="id_content" class="control-label ">Mô tả</label>
        <div class="controls ">
            <textarea class="textarea form-control" cols="40" id="id_content" name="content" rows="10"></textarea>
        </div>
    </div>
    <input class="textinput textInput form-control" id="id_tags" name="tags" type="hidden">
    <div class="form-group">
        <label for="topics" class="control-label ">Chủ đề</label>
        <ul id="topics"></ul>
    </div>    
    <div class="form-group">
        <div class="controls ">
            <input type="submit" name="submit" value="Đăng câu hỏi" class="btn btn-primary" id="submit-id-submit">
        </div>
    </div>
</form>
{%endblock%}

question/templates/question_base.html
{%extends "base.html"%}

question/templates/question_detail.html
{%extends "question_base.html"%}
{% load crispy_forms_tags %}
{%load question_template%}
{%block title%}
    {{question.title|escape}}
{%endblock%}
{%block content%}
    {%if question%}
        <div class="question_detail question">            
            <h4>{{question.title|escape}}</h4>
            <div class="author">
                <a class="thumb" href="{% url 'user:profile' question.author.username%}">
                    {%if question.author.avatar %}
                        <img class="img-circle" src="{{ MEDIA_URL}}{{question.author.avatar}}"/>
                    {%else%}
                        <img class="img-circle" src="{{ MEDIA_URL}}/profiles/noimage.png"/>
                    {%endif%}                
                </a>       
                <a href="{% url 'user:profile' question.author.username%}">
                    {{question.author.fullname|escape}}    
                </a>
            </div>         
            <p>{{question.content|escape}}</p>
            <p><span class="text-info"><small>Chỉnh sửa: {{question.modify|escape}}</small></span></p>
            <hr/>
            <div class="social row">
                <div class="col-md-2 vote">
                    <button class="btn btn-default btn-xs vote">
                        <input type="hidden" name="objectid" value="{{ question.pk }}"/>
                        <input type="hidden" name="votetype" value="vote"/>
                        <input type="hidden" name="objecttype" value="question"/>
                        <span class="glyphicon glyphicon-thumbs-up"></span>
                        <span class="follow_label">
                        Thích
                        </span>
                        <span class="votes_count">{{question.votes_count}}</span>
                    </button>  
                </div>
                <div class="col-md-2 vote">
                    <button class="btn btn-default btn-xs vote">
                        <input type="hidden" name="objectid" value="{{ question.pk }}"/>
                        <input type="hidden" name="votetype" value="downvote"/>
                        <input type="hidden" name="objecttype" value="question"/>
                        <span class="glyphicon glyphicon-thumbs-down"></span>
                        <span class="follow_label">
                        Không thích
                        </span>
                        <span class="votes_count">{{question.downvotes_count}}</span>
                    </button>
                </div>
                <div class="col-md-2">
                    <a href="{% url 'question:detail' question.pk question.slug %}#answers" class="btn btn-link btn-xs">
                    <span class="glyphicon glyphicon-comment"></span> Câu trả lời({{question.question_answers.all.count}})
                    </a>
                </div>
                <div class="col-md-6">
                    {%if question.tags.all%}
                        <span class="glyphicon glyphicon-tags"></span> :
                        {%for tag in question.tags.all%}
                            <a href="{% url 'tag:tag_detail' tag.pk tag.slug %}">{{tag.name}}</a>,
                        {%endfor%}
                    {%endif%}
                </div>
            </div>
            <hr/>
                <div id="answers" class="answers detailBox">
                    <div class="titleBox">
                      <label>Trả lời</label>
                    </div>                    
                    {%if answerform%}
                        <div class="commentBox">
                            {% crispy answerform%}
                        </div>                        
                    {%endif%}
                    {%if answers%}
                        <div class="actionBox">
                            <ul class="commentList">
                                {%for answer in answers%}
                                    {%display_answer answer%}
                                {%endfor%}
                            </ul>   
                        </div>
                    {%endif%}   
                </div>
           
        </div>
    {%else%}
        <p><span class="text-danger">Câu hỏi không tồn tại</span></p>
    {%endif%}
    
{%endblock%}

question/templates/trending_questions.html
{%if questions%}
    <div class="widget-title">
        <h5><span class="glyphicon glyphicon-time"></span> Hot trong tháng</h5>      
    </div>    
    <div class="trending-questions">
    {%for question in questions%}
        <div class="item">
            <a href="{% url 'question:detail' question.pk question.slug %}">{{question.title}}</a>
        </div>
    {%endfor%}
    </div>
{%endif%}