accounts/urls.py
from django.conf.urls import url, patterns
from accounts.views import RegisterView, ProfileView, LoginView, LogoutView,RegisterSuccessView,EditProfileView,FollowUser

urlpatterns=patterns('',
    url(r'^register/$',RegisterView.as_view(),name="register"),
    url(r'^registersuccess/$',RegisterSuccessView.as_view(),name="register_success"),
    url(r'^login/$',LoginView.as_view(), name="login"),
    url(r'^logout/$', LogoutView.as_view(), name="logout"),
    url(r'^profile/(?P<username>[-\w\d]+)/$',ProfileView.as_view(),name="profile"),
    url(r'^profile/$',ProfileView.as_view(),name="myprofile"),
    url(r'^changepassword/$',ProfileView.as_view(),name="change_password"),
    url(r'^editprofile/$',EditProfileView.as_view(),name="edit_profile"),
    url(r'^follow/$',FollowUser.as_view())
)

hoidap/urls.py
from django.conf.urls import include, url, patterns
from django.contrib import admin
from .views import Index,SearchAjax
import settings
urlpatterns = [
    # Examples:
    # url(r'^$', 'hoidap.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^$',Index.as_view(), name="index"),
    url(r'^user/',include('accounts.urls', namespace="user")),
    url(r'^tag/', include('tag.urls',namespace="tag")),
    url(r'^question/', include('question.urls',namespace="question")),
    url(r'^message/', include('messenger.urls', namespace="message")),
    url(r'^notification/', include('notification.urls', namespace="notification")),
    url(r'^search/ajax/$',SearchAjax.as_view(),name="searchajax"),
]
#media files
if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += patterns('',
        (r'^media/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.MEDIA_ROOT}))

#Change title admin    
admin.site.site_header = "Hoi dap"

tag/urls.py
from django.conf.urls import url, patterns
from .views import TagView, AddTagView, TagAllView,TagSearchAjaxView
from accounts.views import FollowTag
urlpatterns=patterns('',
    url(r'^all/$', TagAllView.as_view(), name="all"),
    url(r'^addtag/$', AddTagView.as_view(), name="add"),    
    url(r'^(?P<tagid>\d+)-(?P<slug>[-\w\d]+)/$',TagView.as_view(), name="tag_detail"),
    url(r'^follow/$', FollowTag.as_view(),name="follow_tag"),
    url(r'^search/', TagSearchAjaxView.as_view(),name="search"),
    )

templates/include/_header.html
{%load notification_template%}
{%load messenger_template%}
{%load staticfiles%}
<nav class="navbar navbar-default" role="navigation">
    <div class="container">
        <div class="row">
            <div class="col-md-2">
                <div class="navbar-header">
                    <a class="navbar-brand" href="{% url "index" %}">Tôi hỏi</a>
                </div>
            </div>            
            <div class="col-md-5 search-form">
                <form class="navbar-form" action="/search/" role="search" method="post">
                    <div class="row">
                    <div class="input-group col-md-12">
                        <input type="text" class="form-control" placeholder="Tìm kiếm câu hỏi, chủ đề..." name="term" id="searchtext">
                        <div class="input-group-btn">
                            <button class="btn btn-default" id="search" type="submit">
                                <i class="glyphicon glyphicon-search"></i>
                            </button>
                        </div>
                    </div>
                    </div>
                    <div class="search-results Flyout">                    
                    </div>
                </form>                
            </div>
            {%if user.is_authenticated%}
                <a href="{% url 'question:add' %}" class="btn btn-primary pull-right" id="addquestion"><span class="glyphicon glyphicon-question-sign"></span> Đặt câu hỏi</a>
            {%endif%}
            <ul class="nav navbar-nav pull-right">
                {% if user.is_authenticated %}
                    <li class="activities"><a id="notificationnew" href="#">
                    <span class="glyphicon glyphicon-bell"></span>
                    {%notification_count%}</a>
                        <div class="NotificationsFlyout Flyout">
                            <div class="beeperNubWrapper"><div class="beeperNub"></div></div>
                            <div class="activities-header">
                                <h4 class="pull-left">Thông báo</h4>
                                <a id="markallread" class="pull-right all-read" href="#">Đã đọc</a>
                                <div class="clear"></div>
                            </div>
                            <div class="results"></div>
                            <a class="seeMore" href="{% url 'notification:all' %}">Xem toàn bộ</a>
                        </div>
                    </li>
                    <li class="activities">
                        <a id="messagenew" href="#"><span class="glyphicon glyphicon-comment"></span>{%message_count%}</a>
                        <div class="MessagesFlyout Flyout">
                            <div class="beeperNubWrapper"><div class="beeperNub"></div></div>
                            <div class="activities-header">
                                <h4 class="pull-left">Tin nhắn</h4>
                                <div class="clear"></div>
                            </div>
                            <div class="results"></div>
                            <a class="seeMore" href="{% url 'message:all' %}">Xem toàn bộ</a>
                        </div>                        
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">{{user.profile.fullname}}
                            <b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href="{% url 'user:myprofile' %}">Hồ sơ</a></li>                            
                            <li><a href="{% url 'user:edit_profile' %}">Sửa hồ sơ</a></li>
                            {# <li><a href="{% url 'user:change_password' %}">Change password</a></li> #}
                            <li class="divider"></li>
                            <li><a href="{% url 'user:logout' %}">Đăng xuất</a></li>
                            <li class="divider"></li>                    
                        </ul>
                    </li>
                {% else %}
                    <li><a href="{% url 'user:login' %}">Đăng nhập</a></li>
                    <li><a href="{% url 'user:register' %}">Đăng ký</a></li>
                {% endif %}            
            </ul>            
        </div>        
    </div>
</nav>