hoidap/urls.py
from django.conf.urls import include, url, patterns
from django.contrib import admin
from .views import Index,SearchAjax
import settings
urlpatterns = [
    # Examples:
    # url(r'^$', 'hoidap.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^$',Index.as_view(), name="index"),
    url(r'^user/',include('accounts.urls', namespace="user")),
    url(r'^tag/', include('tag.urls',namespace="tag")),
    url(r'^question/', include('question.urls',namespace="question")),
    url(r'^message/', include('messenger.urls', namespace="message")),
    url(r'^notification/', include('notification.urls', namespace="notification")),
    url(r'^search/ajax/$',SearchAjax.as_view(),name="searchajax"),
]
#media files
if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += patterns('',
        (r'^media/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.MEDIA_ROOT}))

#Change title admin    
admin.site.site_header = "Hoi dap"

notification/urls.py
from django.conf.urls import url, patterns
from .views import NewNotificationsView, AllNotificationsView,ViewNotificationView,MarkAllReadView
urlpatterns=patterns('',
    url(r'^new/$',NewNotificationsView.as_view(), name="new"),
    url(r'^all/$',AllNotificationsView.as_view(), name="all"),
    url(r'^view/(?P<notificationid>\d+)/$', ViewNotificationView.as_view(),name="view"),
    url(r'^markallread/$', MarkAllReadView.as_view(), name="allread"),
    )

tag/urls.py
from django.conf.urls import url, patterns
from .views import TagView, AddTagView, TagAllView,TagSearchAjaxView
from accounts.views import FollowTag
urlpatterns=patterns('',
    url(r'^all/$', TagAllView.as_view(), name="all"),
    url(r'^addtag/$', AddTagView.as_view(), name="add"),    
    url(r'^(?P<tagid>\d+)-(?P<slug>[-\w\d]+)/$',TagView.as_view(), name="tag_detail"),
    url(r'^follow/$', FollowTag.as_view(),name="follow_tag"),
    url(r'^search/', TagSearchAjaxView.as_view(),name="search"),
    )

notification/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models
from django.core.urlresolvers import reverse
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericForeignKey

from accounts.models import UserProfile

# Create your models here.

class Notification(models.Model):
    sender=models.ForeignKey(UserProfile)
    recipient=models.ForeignKey(UserProfile, related_name='notifications')
    action=models.CharField(blank=True, max_length=10)#vote|downvote, answer,addquestion
    content_type = models.ForeignKey(ContentType)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey('content_type', 'object_id')
    create=models.DateTimeField(auto_now=True)
    is_read=models.BooleanField(default=False)

    @property
    def notification_string(self):
        string=""
        if self.action=='vote' or self.action=='downvote':
            if self.content_object.__class__.__name__.lower()=='answer':
                string="{} {} bình luận: \"{}\"".format(self.sender.fullname, 
                self.action,self.content_object.content[:50])
            elif self.content_object.__class__.__name__.lower()=='question':
                string= "{} {} câu hỏi: \"{}\"".format(self.sender.fullname, 
                self.action,self.content_object.title[:50])
        elif self.action=='answer':
            string="{} trả lời câu hỏi: \"{}\"".format(self.sender.fullname,self.content_object.content[:50])
        elif self.action=="addquestion":
            string="{} đăng một câu hỏi:\"{}\"".format(self.sender.fullname, 
                self.content_object.title[:50])
        return string.encode('utf8')
    @property
    def notification_url(self):
        url=""
        if self.content_object.__class__.__name__.lower()=='answer':
            url=reverse('question:detail', args=(self.content_object.question.pk,
                self.content_object.question.slug))
        elif self.content_object.__class__.__name__.lower()=='question':
            url=reverse('question:detail', args=(self.content_object.pk,self.content_object.slug))                
        return url

notification/views.py
from __future__ import unicode_literals
from django.shortcuts import render
from django.views.generic import View
from django.core.exceptions import ObjectDoesNotExist
from django.http import HttpResponseRedirect
from utils.login_require import LoginRequiredMixin
from .models import Notification
# Create your views here.

class NewNotificationsView(LoginRequiredMixin,View):
    def get(self, request):
        args={}
        notifications=Notification.objects.filter(recipient=request.user.profile, is_read=False).order_by('-create')
        if len(notifications) < 10:
            notifications=Notification.objects.filter(recipient=request.user.profile).order_by('-create')[:10]
        args['notifications']=notifications
        return render(request, 'new_notification.html',args)

class AllNotificationsView(LoginRequiredMixin, View):
    def get(self, request):
        notifications=Notification.objects.all().order_by('-create')[:30]
        args={}
        args['notifications']=notifications
        return render(request, 'all_notification.html',args)

class ViewNotificationView(LoginRequiredMixin,View):
    def get(self,request,notificationid):        
        try:
            notification=Notification.objects.get(pk=notificationid)
            if not notification.is_read:                
                notification.is_read=True
                notification.save()
        except ObjectDoesNotExist:            
            pass
        return HttpResponseRedirect(notification.notification_url)

class MarkAllReadView(LoginRequiredMixin, View):
    def get(self, request):
        notifications=Notification.objects.filter(recipient=request.user.profile, is_read=False)
        if notifications:
            for notification in notifications:
                notification.is_read=True
                notification.save()
        notifications=Notification.objects.filter(recipient=request.user.profile).order_by('-create')[:10]
        args={}
        args['notifications']=notifications
        return render(request, 'new_notification.html',args)

notification/templates/all_notification.html
{%extends "base.html"%}
{%block title%}Thông báo{%endblock%}
{%block content%}
<h4>Thông báo</h4>
<hr/>
{%if notifications%}
    <div id="notifications">
    {%for notification in notifications%}
        <div class="notification item {%if not notification.is_read %}unread{%endif%}">
            <a class="thumb" href="{% url 'notification:view' notification.pk %}">
                {%if profile.avatar %}
                    <img class="img-circle" src="{{ MEDIA_URL}}{{notification.sender.avatar}}"/>
                {%else%}
                    <img class="img-circle" src="{{ MEDIA_URL}}/profiles/noimage.png"/>
                {%endif%}
            </a>
            <a href="{% url 'notification:view' notification.pk %}">
                <div>{{notification.notification_string}}</div>
                <div><small>{{notification.create}}</small></div>
            </a>
            <div class="clear"></div>
        </div>
    {%endfor%}
    </div>
{%endif%}
{%endblock%}

notification/templates/new_notification.html
{%if notifications%}
    <div id="notifications" class="ajax-notification">
    {%for notification in notifications%}
        <div class="notification item {%if not notification.is_read %}unread{%endif%}">
            <a class="thumb" href="{% url 'notification:view' notification.pk %}">
                {%if notification.sender.avatar %}
                    <img class="img-circle" src="{{ MEDIA_URL}}{{notification.sender.avatar}}"/>
                {%else%}
                    <img class="img-circle" src="{{ MEDIA_URL}}/profiles/noimage.png"/>
                {%endif%}
            </a>
            <a class="title" href="{% url 'notification:view' notification.pk %}">
                <div>{{notification.notification_string}}</div>
                <div><small>{{notification.create}}</small></div>
            </a>
            <div class="clear"></div>
        </div>
    {%endfor%}
    </div>
{%else%}
<p>Không tìm thấy kết quả<p>
{%endif%}

notification/templates/new_notification_count.html
{%if count > 0 %}
    <span class="count_activities">{{count}}</span>
{%endif%}