accounts/urls.py
from django.conf.urls import url, patterns
from accounts.views import RegisterView, ProfileView, LoginView, LogoutView,RegisterSuccessView,EditProfileView,FollowUser

urlpatterns=patterns('',
    url(r'^register/$',RegisterView.as_view(),name="register"),
    url(r'^registersuccess/$',RegisterSuccessView.as_view(),name="register_success"),
    url(r'^login/$',LoginView.as_view(), name="login"),
    url(r'^logout/$', LogoutView.as_view(), name="logout"),
    url(r'^profile/(?P<username>[-\w\d]+)/$',ProfileView.as_view(),name="profile"),
    url(r'^profile/$',ProfileView.as_view(),name="myprofile"),
    url(r'^changepassword/$',ProfileView.as_view(),name="change_password"),
    url(r'^editprofile/$',EditProfileView.as_view(),name="edit_profile"),
    url(r'^follow/$',FollowUser.as_view())
)

hoidap/urls.py
from django.conf.urls import include, url, patterns
from django.contrib import admin
from .views import Index,SearchAjax
import settings
urlpatterns = [
    # Examples:
    # url(r'^$', 'hoidap.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^$',Index.as_view(), name="index"),
    url(r'^user/',include('accounts.urls', namespace="user")),
    url(r'^tag/', include('tag.urls',namespace="tag")),
    url(r'^question/', include('question.urls',namespace="question")),
    url(r'^message/', include('messenger.urls', namespace="message")),
    url(r'^notification/', include('notification.urls', namespace="notification")),
    url(r'^search/ajax/$',SearchAjax.as_view(),name="searchajax"),
]
#media files
if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += patterns('',
        (r'^media/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.MEDIA_ROOT}))

#Change title admin    
admin.site.site_header = "Hoi dap"

messenger/urls.py
from django.conf.urls import url, patterns
from .views import ConversationView, AllConversationView, SendMessageView,NewConversationView, NewMessageAjaxView
urlpatterns=patterns('',
    url(r'^all/$', AllConversationView.as_view(), name="all"),
    url(r'^t/(?P<username>[-\w\d]+)/$', ConversationView.as_view(), name="view_conversation"),
    url(r'^send/(?P<username>[-\w\d]+)/$', SendMessageView.as_view(), name="send"),
    url(r'^new/$',NewConversationView.as_view(), name="new"),
    url(r'^newajax/(?P<username>[-\w\d]+)/$',NewMessageAjaxView.as_view(), name="newajax"),
    )

question/urls.py
from django.conf.urls import url, patterns
from .views import AddQuestionView, QuestionView, AddAnswerView, VoteView

urlpatterns=patterns('',
    url(r'^add/$', AddQuestionView.as_view(), name="add"),
    url(r'^(?P<questionid>\d+)-(?P<slug>[-\w\d]+)/$',QuestionView.as_view(), name="detail"),
    url(r'^(?P<questionid>\d+)-(?P<slug>[-\w\d]+)/answer/$',AddAnswerView.as_view(), name="answer"),
    url(r'^vote/$', VoteView.as_view(), name="vote"),
    )

tag/urls.py
from django.conf.urls import url, patterns
from .views import TagView, AddTagView, TagAllView,TagSearchAjaxView
from accounts.views import FollowTag
urlpatterns=patterns('',
    url(r'^all/$', TagAllView.as_view(), name="all"),
    url(r'^addtag/$', AddTagView.as_view(), name="add"),    
    url(r'^(?P<tagid>\d+)-(?P<slug>[-\w\d]+)/$',TagView.as_view(), name="tag_detail"),
    url(r'^follow/$', FollowTag.as_view(),name="follow_tag"),
    url(r'^search/', TagSearchAjaxView.as_view(),name="search"),
    )

accounts/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from time import time
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from tag.models import Tag
# Create your models here.
def get_profile_url(instance, filename):
    return "profiles/{}_{}".format(str(time()).replace('.','_'),filename)

class UserProfile(models.Model):
    user=models.OneToOneField(User, unique=True, related_name='profile')
    website=models.URLField(max_length=100,blank=True)
    avatar=models.ImageField(upload_to=get_profile_url,blank=True)
    address=models.CharField(blank=True, max_length=255)
    birthday=models.DateField(null=True)
    gender=models.CharField(blank=True, choices=(('Nam','Nam'),('Nữ','Nữ')), max_length=10)
    bio=models.TextField(blank=True)
    rank=models.FloatField(default=0)    
    follows_count=models.IntegerField(default=0)
    followers_count=models.IntegerField(default=0)
    follows=models.ManyToManyField('self', related_name='followers', blank=True, symmetrical=False)
    follow_tags=models.ManyToManyField(Tag, related_name='tag_followers', blank=True)

    @property
    def fullname(self):
        return self.user.first_name+" "+self.user.last_name

    @property
    def username(self):
        return self.user.username
        
    @property
    def questions_count(self):
        return self.user_questions.all().count()

    @property
    def answers_count(self):
        return self.user_answers.all().count()

    def __str__(self):
        return self.user.username

    def save(self,*args, **kwargs):
        if self.pk:
            self.follows_count=self.follows.all().count()
            self.followers_count= self.followers.all().count()
        super(UserProfile, self).save(*args, **kwargs)


def create_profile(sender,instance,created,**kwargs):
    if created:
        profile,created=UserProfile.objects.get_or_create(user=instance)

post_save.connect(create_profile,sender=User)

accounts/forms.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django import forms
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from accounts.models import UserProfile
from django.forms.extras.widgets import SelectDateWidget

class RegistrationForm(UserCreationForm):
    email = forms.EmailField(required=True)
    first_name = forms.CharField(required=False, label='Họ đệm')
    last_name = forms.CharField(required=False, label='Tên')
    username=forms.CharField(required=True, label='Tên đăng nhập')
    password1=forms.CharField(required=True, label='Mật khẩu', widget=forms.PasswordInput)
    password2=forms.CharField(required=True, label='Xác nhận mật khẩu', widget=forms.PasswordInput)
    class Meta:
        model = User
        fields = ('first_name', 'last_name','username','password1', 'password2', "email",)

    def __init__(self, *args, **kwargs):
        super(RegistrationForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_id = 'register'
        self.helper.form_method = 'post'
        self.helper.form_action = 'user:register'
        self.helper.add_input(Submit('submit', 'Đăng ký'))

    def save(self,commit = True):   
        user = super(RegistrationForm, self).save(commit = False)
        user.set_password(self.cleaned_data['password1'])
        user.email = self.cleaned_data['email']
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.is_active=True
        if commit:
            user.save()
        return user    

    def clean(self):
        cleaned_data = super(RegistrationForm, self).clean()
        if 'password1' in self.cleaned_data and 'password2' in self.cleaned_data:
            #check password match
            if self.cleaned_data['password1'] != self.cleaned_data['password2']:
                raise forms.ValidationError("Mật khẩu không trùng khớp.")
        return self.cleaned_data

    def clean_email(self):        
        if User.objects.filter(email__iexact=self.cleaned_data['email']).count():
            raise forms.ValidationError(u'Email đã tồn tại')
        return self.cleaned_data['email']

class LoginForm(forms.Form):
    username=forms.CharField(label=u'Tên đăng nhập',widget=forms.widgets.TextInput(), required=True)
    password=forms.CharField(label=u'Mật khẩu',widget=forms.widgets.PasswordInput(),required=True)
    class Meta:
        fields=['username','password']

    def __init__(self, *args, **kwargs):
        super(LoginForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_id = 'login'
        self.helper.form_method = 'post'
        self.helper.form_action = 'user:login'
        self.helper.add_input(Submit('submit', 'Đăng nhập')) 

class UserProfileForm(forms.ModelForm):
    birthday=forms.DateField(widget=forms.widgets.DateInput(format="%m/%d/%Y"), label='Ngày sinh')
    address=forms.CharField(label='Địa chỉ')
    gender=forms.ChoiceField(label='Giới tính',choices=(('Nam','Nam'),('Nữ','Nữ')))
    bio=forms.CharField(widget=forms.Textarea, label='Tiểu sử')
    avatar=forms.ImageField(label='Ảnh đại diện')
    class Meta:
        model = UserProfile
        exclude=('user','rank','follows','followers_count','follows_count','follow_tags')

    def __init__(self, *args, **kwargs):
        super(UserProfileForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_id = 'editprofile'
        self.helper.form_method = 'post'
        self.helper.form_action = 'user:edit_profile'
        self.helper.add_input(Submit('submit', 'Cập nhật'))

accounts/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
import json
from django.shortcuts import render
from django.views.generic import View
from django.core.context_processors import csrf 
from django.contrib.auth import login,authenticate,logout
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect
from django.http import HttpResponse
from django.core.urlresolvers import reverse
from django.core.exceptions import ObjectDoesNotExist
from utils.login_require import LoginRequiredMixin

from .forms import RegistrationForm,LoginForm,UserProfileForm
from .models import UserProfile
from tag.models import Tag
# Create your views here.

class RegisterView(View):
    def get(self, request):
        args={}
        args.update(csrf(request))
        form=RegistrationForm()
        args['form']=form
        return render(request, 'registration.html',args)

    def post(self, request):
        form = RegistrationForm(data=request.POST)        
        if form.is_valid():
            form.save()
            user = authenticate(username=form.cleaned_data['username'],
                password=form.cleaned_data['password1'])
            login(request, user)            
            return HttpResponseRedirect(reverse('user:register_success'))
        else:
            args={}
            args.update(csrf(request))
            args['form']=form
            return render(request, 'registration.html',args)
class RegisterSuccessView(View):
    def get(self, request):
        return render(request, 'registration_success.html',{})

class LoginView(View):
    def get(self, request):
        if request.user.is_authenticated():
            return HttpResponseRedirect(reverse('index'))
        args={}
        args.update(csrf(request))
        form=LoginForm()
        args['form']=form
        return render(request, 'login.html', args)

    def post(self, request):
        args={}
        form=LoginForm(data=request.POST)
        if form.is_valid():
            try:
                user = authenticate(username=form.cleaned_data['username'], password=form.cleaned_data['password'])
            except ObjectDoesNotExist:
                try:
                    user=User.objects.get(email=form.cleaned_data['username'])
                    if user is not None and user.check_password(form.cleaned_data['password']):                    
                        user=authenticate(username=user.username, password=form.cleaned_data['password'])
                except ObjectDoesNotExist:
                    user=None
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return HttpResponseRedirect(reverse('index'))
                else:
                    args['message']='Bạn đang bị vô hiệu hóa.'
            else:
                args['message']='Tên đăng nhập hoặc mật khẩu không đúng.'
        args['form']=form
        return render(request,'login.html',args)
class LogoutView(LoginRequiredMixin,View):
    def get(self, request):
        logout(request)
        return HttpResponseRedirect(reverse('index'))

class ProfileView(View):
    def get(self, request, username=None):
        args={}
        if username:
            #profile of another user
            try:
                user=User.objects.get(username=username)
                if user==request.user:
                    return HttpResponseRedirect(reverse('user:myprofile'))
                profile=user.profile
                args['profile']=profile
            except User.DoesNotExist:
                pass                
        else:
            #my profile
            if request.user.is_authenticated():
                profile=request.user.profile
                followers=profile.followers.all()
                follows=profile.follows.all()
                args['followers']=followers
                args['follows']=follows
                args['profile']=profile
            else:
                return HttpResponseRedirect(reverse('user:login'))
        args.update(csrf(request))        
        return render(request,'profile_index.html',args)

class EditProfileView(LoginRequiredMixin,View):
    def get(self,request):
        profile=UserProfile.objects.get(user=request.user)
        form=UserProfileForm(instance=profile)
        args={}
        args.update(csrf(request))
        args['form']=form
        return render(request,'editprofile.html',args)

    def post(self,request):
        form=UserProfileForm(request.POST,request.FILES,instance=request.user.profile)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('user:myprofile'))
        else:
            args={}
            args.update(csrf(request))
            args['form']=form
            return render(request,'editprofile.html',args)

class FollowUser(View):
    def post(self,request):
        message={}
        if request.user.is_authenticated():
            username=request.POST.get('username','')
            if username:
                try:
                    user=User.objects.get(username=username)
                    if user.profile not in request.user.profile.follows.all():
                        request.user.profile.follows.add(user.profile)
                        request.user.profile.save()
                        user.profile.rank+=0.05
                        user.profile.save()
                        message['status']='OK'
                        message['message']=''
                        message['followers_count']=user.profile.followers_count
                        message['label']='Bỏ theo dõi'
                    else:
                        request.user.profile.follows.remove(user.profile)
                        request.user.profile.save()
                        user.profile.rank-=0.05
                        user.profile.save()
                        message['status']='OK'
                        message['followers_count']=user.profile.followers_count
                        message['label']='Theo dõi'
                        message['message']=''
                except User.DoesNotExist:
                    message['status']='False'
                    message['message']='User không tồn tại'       
        else:
            message['message']='Bạn cần đăng nhập'
            message['status']='False'
        return HttpResponse(json.dumps(message), content_type = "application/json")

class FollowTag(View):
    def post(self,request):
        message={}
        if request.user.is_authenticated():
            tagid=request.POST.get('tagid','')
            if tagid:
                try: 
                    tag=Tag.objects.get(pk=tagid)
                    if request.user.profile not in tag.tag_followers.all():
                        #follow
                        request.user.profile.follow_tags.add(tag)
                        request.user.profile.save()
                        tag.save()
                        message['status']='OK'
                        message['message']=''
                        message['followers_count']=tag.followers_count
                        message['label']='Bỏ theo dõi'
                    else:
                        #unfollow
                        request.user.profile.follow_tags.remove(tag)
                        request.user.profile.save()
                        tag.save()
                        message['status']='OK'
                        message['message']=''
                        message['followers_count']=tag.followers_count
                        message['label']='Theo dõi'
                except Tag.DoesNotExist:
                    message['status']='False'
                    message['message']='Chủ đề không tồn tại'
            else:
                message['message']='Chủ đề không tồn tại'
                message['status']='False'
        else:
            message['message']='Bạn cần đăng nhập'
            message['status']='False'
        return HttpResponse(json.dumps(message), content_type = "application/json")

class ChangePasswordView(LoginRequiredMixin,View):
    pass

accounts/templates/editprofile.html
{%extends "base.html"%}
{% load crispy_forms_tags %}
{%block title%}
Sửa hồ sơ - Tôi hỏi
{%endblock%}
{% block content %}
<div class="row">
    <div class="col-md-6">
        {% crispy form%}
    </div>
</div>
{% endblock %}

accounts/templates/list_users.html
{% load static %}
<div class="row user-list">        
    {%for profile in profiles%}
        <div class="item col-md-2">
            <a class="thumb" href="{% url 'user:profile' profile.username %}">
                {%if profile.avatar%}
                    <img class="img-circle"  src="{{ MEDIA_URL }}{{profile.avatar}}"/>
                {%else%}
                    <img class="img-circle"  src="{{ MEDIA_URL }}profiles/noimage.png"/>
                {%endif%}                    
            </a>
            <a href="{% url 'user:profile' profile.username %}">
                {{profile.fullname|escape}}
            </a>
            {%if user.is_authenticated%}                
            {%ifnotequal user.username profile.username%}
            <div class="follow">
                <button class="btn btn-primary btn-xs followuser">
                    <input type="hidden" name="follow" value="{{ profile.username }}"/>
                    <span class="glyphicon glyphicon-plus"></span>
                    <span class="follow_label">
                        {% if user.profile in profile.followers.all%}
                            Bỏ theo dõi
                        {%else%}
                            Theo dõi
                        {%endif%}
                    </span>
                    <span class="followers_count">{{profile.followers_count}}</span>
                </button>
            </div>
            {%endifnotequal%}
            {%endif%}               
        </div>
    {%endfor%}
</div>

accounts/templates/login.html
{%extends "base.html"%}
{% load crispy_forms_tags %}
{%block title%}
Đăng nhập - Tôi hỏi
{%endblock%}
{%block content%}
<div class="row">
    {%if message%}
        <p class="text-danger">{{message}}</p>
    {%endif%}
    <div class="col-md-6">
        {% crispy form%}
    </div>    
</div>
{%endblock%}

accounts/templates/profile_base.html
{% extends "base.html" %}
{% load staticfiles %}
{%block extra_js%}
<script type="text/javascript" src="{% static "js/follow.js" %}"></script>
{%endblock%}

{% block title %}Hồ sơ{% endblock %}

{% block sidebar_left %}
{%if profile %}
    {%if profile.avatar %}
        <img class="img-circle" src="{{ MEDIA_URL}}{{profile.avatar}}"/>
    {%else%}
        <img class="img-circle" src="{{ MEDIA_URL}}/profiles/noimage.png"/>
    {%endif%}
    <hr/>
    <h4>Thông tin</h4>
    <p>Điểm : {{profile.rank}}</p>
    <p><a href="{{profile.website}}">{{profile.website|escape}}</a></p>
    <p>Địa chỉ : {{profile.address|escape}}</p>
    <p>Ngày sinh : {{profile.birthday|escape}}</p>
    <p>Giới tính : {{profile.gender|escape}}</p>
    <hr/>
    <h4>Dòng tin</h4>
    <p>Câu hỏi : <span class="text-info">{{profile.questions_count}}</span></p>
    <p>Trả lời : <span class="text-info">{{profile.answers_count}}</span></p>
    <p>Ngừoi theo dõi : <span class="text-info">{{profile.followers_count}}</span></p>
    <p>Theo dõi : <span class="text-info">{{profile.follows_count}}</span></p>
{%endif%}
{% endblock %}

{% block content %}
    {%csrf_token%}
    {%if profile %}
        <h3>{{profile.fullname|escape}}</h3>
        <p>{{profile.bio|escape}}</p>        
            {% if profile.username != user.username and user.is_authenticated%}
            <div class="row">
            <div class="follow col-md-3">
                <button class="btn btn-primary btn-xs followuser">
                    <input type="hidden" name="follow" value="{{ profile.username }}"/>
                    <span class="glyphicon glyphicon-plus"></span>
                    <span class="follow_label">
                        {% if user.profile in profile.followers.all%}
                            Bỏ theo dõi
                        {%else%}
                            Theo dõi
                        {%endif%}
                    </span>
                    <span class="followers_count">{{profile.followers_count}}</span>
                </button>
            </div>
            <div class="col-md-3 send-message">
                <a href="{% url 'message:view_conversation' profile.username %}">Gửi tin nhắn</a>
            </div>
            </div>         
            {% endif %}
        <hr/>
        {%block profile_content%}
        {%endblock%}
    {%else%}
        <p style="text-warning">User không tồn tại.</p>
    {%endif%}    
{% endblock %}

accounts/templates/profile_index.html
{% extends "profile_base.html" %}
{%load user_template %}
{%block profile_content%}
{%if profile.followers.all %}
<h4>Ngừoi theo dõi</h4>
    {% list_users profile.followers.all%}    
    <hr/>
{%endif%}
{%if profile.follows.all %}
<h4>Theo dõi</h4>
    {% list_users profile.follows.all%}    
    <hr/>
{%endif%}
{%if profile.user_questions%}
    <h4>Câu hỏi</h4>
    <div class="questions">
        {%for question in profile.user_questions.all%}
            <div class="item">
                <a href="{% url 'question:detail' question.pk question.slug %}">{{question.title}}</a>
            </div>
        {%endfor%}
    </div>
{%endif%}
{%if profile.user_answers%}
    <h4>Trả lời</h4>
    <div class="answers">
        {%for answer in profile.user_answers.all%}
            <div class="item">
            Trả lời:
                <a href="{% url 'question:detail' answer.question.pk answer.question.slug %}">{{answer.question.title}}</a>
            </div>
        {%endfor%}
    </div>
{%endif%}
{%endblock%}

accounts/templates/registration.html
{%extends "base.html"%}
{% load crispy_forms_tags %}
{%block title%}
Đăng ký
{%endblock%}
{%block content%}
<h3>Đăng ký</h3>
<hr/>
<div class="row">
    <div class="col-md-6">
        {% crispy form %}
    </div>
</div>
{%endblock%}

accounts/templates/registration_success.html
{%extends "base.html"%}
{% block extra_js %}
<script type="text/javascript">
    $(document).ready(function () {
        window.setTimeout(function () {
            location.href = "{% url 'tag:all' %}";
        }, 3000);
    });
</script>
{% endblock %}
{%block content %}
    <p class="text-success">Đăng ký thành công, bạn sẽ được chuyển đến trang chủ đề(topic) trong giây lát.</p>
{%endblock%}

accounts/templates/top_users.html
{%if profiles %}
    <h4>Top users</h4>
    <div class="top-users">
        {%for profile in profiles%}
            <div class="item">
                <a href="{% url 'user:profile' profile.username %}">{{profile.fullname}}</a>
                <span class="badge">{{profile.rank}}</span>
            </div>
        {%endfor%}
    </div>
{%endif%}